#!/usr/bin/env bash

# This script require Docker / Docker-Compose

echo "Starting Redis/Memcached with Docker ..."
docker-compose up -d

echo "Running tests ..."
go clean -testcache `go list ./... | grep -v example`
gotestsum -- -coverprofile=cover.out `go list ./... | grep -v example`
go tool cover -func cover.out
rm cover.out

echo "Killing Redis/Memcached ..."
docker-compose down
